### ISSUE TITLE
transfer repo to lab

### ISSUE THREAD

**Issue by fgnievinski** [ufrgs-gnss-lab/geo-alhazen#28]
https://github.com/ufrgs-gnss-lab

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by vitorhjr** [comment]
I send the request to transfer the geo-alhazen repo to the ufrgs-gnss-lab organization. 

I am waiting for the response to finish the transfer process.

**Comment by fgnievinski** [comment]
---------- Forwarded message ---------
From: GitHub <support@github.com>
Date: Mon, Jan 16, 2023 at 11:48 AM
Subject: [GitHub] Repository transfer from @vitorhjr (vitorhjr/geo-alhazen)
To:


Hello ufrgs-gnss-lab Owner,

@vitorhjr has transferred the vitorhjr/geo-alhazen repository to ufrgs-gnss-lab/geo-alhazen.

No further action is required at this time.

Questions? Problems? Please visit https://support.github.com/ any time.

Thanks,
Your friends at GitHub

**Comment by fgnievinski** [comment]
https://github.com/vitorhjr/geo-alhazen now redirects to
https://github.com/ufrgs-gnss-lab/geo-alhazen
