### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by fgnievinski** [ufrgs-gnss-lab/geo-alhazen#30]
requirements:
- #27 
- #25
- #33 
- #29

**Comment by fgnievinski** [comment]
adopting [semantic versioning](http://semver.org/),
I think the new number should be v.2.1.0
(and v2.0.0 should have been v1.1.0)

**Comment by vitorhjr** [comment]
The pull request is ready https://github.com/ufrgs-gnss-lab/geo-alhazen/pull/35

**Comment by vitorhjr** [comment]
Dev branch merged to the main trunk.

**Comment by vitorhjr** [comment]
Version 2.1.0 released: https://github.com/ufrgs-gnss-lab/geo-alhazen/releases/tag/2.1.0
